import { LifeTemplate } from '@/features/templates/template-types';

/**
 * The first official Template catalog (v0.4.0). Each entry is a real
 * recurrence shape someone would actually want, not just a category+title
 * shortcut — see `LifeTemplate` for why `defaultOffsetDays` is missing on
 * document/insurance/warranty templates.
 */
export const templateCatalog: LifeTemplate[] = [
  {
    id: 'passport-renewal',
    title: '護照換發',
    category: 'document',
    description: '效期到期前，分階段提醒你準備換發',
    recurrence: 'none',
    recurrenceMode: 'fixed_schedule',
    reminderDays: [180, 90, 30, 7],
    notePlaceholder: '護照號碼',
    featured: true,
  },
  {
    id: 'drivers-license-renewal',
    title: '駕照換發',
    category: 'document',
    description: '到期前提醒換發，不用臨時抱佛腳',
    recurrence: 'none',
    recurrenceMode: 'fixed_schedule',
    reminderDays: [90, 30, 7],
    notePlaceholder: '駕照字號',
  },
  {
    id: 'car-insurance-renewal',
    title: '汽車保險續保',
    category: 'vehicle',
    description: '固定每年續保，不會因晚一天處理而往後漂移',
    recurrence: 'yearly',
    recurrenceMode: 'fixed_schedule',
    reminderDays: [30, 14, 7],
    notePlaceholder: '保單號碼、保險公司',
    featured: true,
  },
  {
    id: 'scooter-insurance-renewal',
    title: '機車保險續保',
    category: 'vehicle',
    description: '固定每年續保，不會因晚一天處理而往後漂移',
    recurrence: 'yearly',
    recurrenceMode: 'fixed_schedule',
    reminderDays: [30, 14, 7],
    notePlaceholder: '保單號碼、保險公司',
  },
  {
    id: 'car-maintenance',
    title: '汽車定期保養',
    category: 'vehicle',
    description: '完成後重新計算下一次保養時間',
    defaultOffsetDays: 90,
    recurrence: 'quarterly',
    recurrenceMode: 'from_completion',
    reminderDays: [7, 1],
    notePlaceholder: '上次保養里程數',
  },
  {
    id: 'scooter-maintenance',
    title: '機車定期保養',
    category: 'vehicle',
    description: '完成後重新計算下一次保養時間',
    defaultOffsetDays: 90,
    recurrence: 'quarterly',
    recurrenceMode: 'from_completion',
    reminderDays: [7, 1],
    notePlaceholder: '上次保養里程數',
  },
  {
    id: 'water-filter-replacement',
    title: '濾芯更換',
    category: 'home',
    description: '完成後重新計算下一次更換時間',
    defaultOffsetDays: 90,
    recurrence: 'quarterly',
    recurrenceMode: 'from_completion',
    reminderDays: [7, 1],
    notePlaceholder: '濾芯型號',
    featured: true,
  },
  {
    id: 'ac-cleaning',
    title: '冷氣清洗',
    category: 'home',
    description: '完成後重新計算下一次清洗時間',
    defaultOffsetDays: 180,
    recurrence: 'yearly',
    recurrenceMode: 'from_completion',
    reminderDays: [30, 7],
    featured: true,
  },
  {
    id: 'water-purifier-maintenance',
    title: '淨水器保養',
    category: 'home',
    description: '完成後重新計算下一次保養時間',
    defaultOffsetDays: 90,
    recurrence: 'quarterly',
    recurrenceMode: 'from_completion',
    reminderDays: [7, 1],
    notePlaceholder: '濾心型號',
  },
  {
    id: 'toothbrush-head-replacement',
    title: '牙刷刷頭更換',
    category: 'home',
    description: '完成後重新計算下一次更換時間',
    defaultOffsetDays: 90,
    recurrence: 'quarterly',
    recurrenceMode: 'from_completion',
    reminderDays: [7, 1],
  },
  {
    id: 'phone-warranty',
    title: '手機保固到期',
    category: 'digital',
    description: '保固到期前提醒你，別讓保固悄悄過期',
    recurrence: 'none',
    recurrenceMode: 'fixed_schedule',
    reminderDays: [30, 7],
    notePlaceholder: '購買門市、序號',
  },
  {
    id: 'appliance-warranty',
    title: '家電保固到期',
    category: 'digital',
    description: '保固到期前提醒你，別讓保固悄悄過期',
    recurrence: 'none',
    recurrenceMode: 'fixed_schedule',
    reminderDays: [30, 7],
    notePlaceholder: '購買門市、序號',
  },
  {
    id: 'domain-renewal',
    title: '網域續費',
    category: 'digital',
    description: '固定每年續費，不會因晚一天處理而往後漂移',
    recurrence: 'yearly',
    recurrenceMode: 'fixed_schedule',
    reminderDays: [30, 14, 7],
    notePlaceholder: '網域名稱、註冊商',
  },
  {
    id: 'free-trial-cancellation',
    title: '免費試用取消',
    category: 'money',
    description: '試用到期前提醒取消，避免被扣款',
    defaultOffsetDays: 7,
    recurrence: 'none',
    recurrenceMode: 'fixed_schedule',
    reminderDays: [3, 1, 0],
    notePlaceholder: '服務名稱',
    featured: true,
  },
  {
    id: 'subscription-renewal',
    title: '訂閱服務續費',
    category: 'money',
    description: '固定扣款週期，提前幾天提醒你檢查要不要繼續',
    defaultOffsetDays: 30,
    recurrence: 'monthly',
    recurrenceMode: 'fixed_schedule',
    reminderDays: [7, 3, 1],
    notePlaceholder: '服務名稱、方案',
    featured: true,
  },
  {
    id: 'credit-card-annual-fee',
    title: '信用卡年費',
    category: 'money',
    description: '固定每年收費，提前提醒你評估是否續用',
    recurrence: 'yearly',
    recurrenceMode: 'fixed_schedule',
    reminderDays: [30, 7],
    notePlaceholder: '卡片名稱',
  },
  {
    id: 'travel-document-check',
    title: '旅行證件確認',
    category: 'travel',
    description: '出發前確認證件效期，安心出門',
    recurrence: 'none',
    recurrenceMode: 'fixed_schedule',
    reminderDays: [30, 14, 7],
  },
  {
    id: 'visa-expiration',
    title: '簽證到期',
    category: 'travel',
    description: '簽證到期前提醒，避免逾期停留風險',
    recurrence: 'none',
    recurrenceMode: 'fixed_schedule',
    reminderDays: [90, 30, 7],
    notePlaceholder: '簽證類型、目的地',
  },
];
